- name: Install tools for '22.630 Computer structure'subject
  block:
    - name: Install packages
      apt:
        name:
        - build-essential
        - cmake
        - extra-cmake-modules
        - yasm
        - kdbg
        - geany
        - geany-plugins
    - become_user: "{{ default_user }}"
      vars:
        geany_filedefs_dir: ~/.config/geany/filedefs/
      block:
        - name: Create Geany configuration folder
          file:
            path: "{{ geany_filedefs_dir}}"
            state: directory
        - name: Configure Geany for assembler
          copy:
            src: filetypes.asm
            dest: "{{ geany_filedefs_dir}}/filetypes.asm"
    - name: Configure Kdbg
      become_user: "{{ default_user }}"
      ansible.builtin.lineinfile:
        state: present
        create: true
        path: ~/.gdbinit
        regexp: 'set disassembly-flavor'
        line: set disassembly-flavor intel